export const GUITARS = {
  warpig: {
    name: 'WARPIG',
    slug: 'warpig',
    heroPreview: '/guitars/warpig/hero-small.webp',
    heroFull: '/guitars/warpig/hero-full.webp',
    thumb: '/guitars/warpig/thumb.webp',
    bg: '/guitars/warpig/bg.webp',
    galleryManifest: '/guitars/warpig/gallery/manifest.json',
    images: [
      '/guitars/warpig/gallery/1_w800.jpg',
      '/guitars/warpig/gallery/2_w800.jpg',
      '/guitars/warpig/gallery/3_w800.jpg',
      '/guitars/warpig/gallery/4_w800.jpg',
      '/guitars/warpig/gallery/5_w800.jpg',
      '/guitars/warpig/gallery/6_w800.jpg',
    ],
    specs: [
      'Body: Mahogany',
      'Neck: Maple',
      'Fretboard: Rosewood',
      'Construction: Set-in',
      'Fretboard radius: 10"',
      'Scale length: 24.5"',
      'Frets: 22 jumbo',
      'Pickup: Bridge 16.5k, Neck 7.5k',
      'Nut: Bone',
      'Potentiometers: 500k',
      'Bridge: Locking roller',
    ],
  },

  ravenhawk: {
    name: 'RAVENHAWK',
    slug: 'ravenhawk',
    heroPreview: '/guitars/ravenhawk/hero-small.webp',
    heroFull: '/guitars/ravenhawk/hero-full.webp',
    thumb: '/guitars/ravenhawk/thumb.webp',
    bg: '/guitars/ravenhawk/bg.webp',
    galleryManifest: '/guitars/ravenhawk/gallery/manifest.json',
    images: [
      '/guitars/ravenhawk/gallery/1_w800.jpg',
      '/guitars/ravenhawk/gallery/2_w800.jpg',
      '/guitars/ravenhawk/gallery/3_w800.jpg',
      '/guitars/ravenhawk/gallery/4_w800.jpg',
      '/guitars/ravenhawk/gallery/5_w800.jpg',
      '/guitars/ravenhawk/gallery/6_w800.jpg',
    ],
    specs: [
      'Model: 7 string',
      'Body: Mahogany',
      'Color: Matte Black Finish',
      'Neck: Maple',
      'Fretboard: Rosewood',
      'Inlays: Dot',
      'Construction: Set-in neck',
      'Scale: 24.5"',
      'Frets: 22 jumbo',
      'Pickup: HH',
      'Bridge: Tune o matic',
      'Nut: Plastic',
      'Potentiometers: 500k',
      'Switches: 1 vol, 1 tone, 3 toggle',
      'Hardware: Chrome',
      'Tuners: Locking',
    ],
  },

  specter: {
    name: 'SPECTER',
    slug: 'specter',
    heroPreview: '/guitars/specter/hero-small.webp',
    heroFull: '/guitars/specter/hero-full.webp',
    thumb: '/guitars/specter/thumb.webp',
    bg: '/guitars/specter/bg.webp',
    galleryManifest: '/guitars/specter/gallery/manifest.json',
    images: [
      '/guitars/specter/gallery/1_w800.jpg',
      '/guitars/specter/gallery/2_w800.jpg',
      '/guitars/specter/gallery/3_w800.jpg',
    ],
    specs: [
      'Body: Double cutaway mahogany',
      'Neck: Maple',
      'Fretboard: Rosewood',
      'Inlays: Pearl trapezoid',
      'Construction: Set-in',
      'Fretboard radius: 12"',
      'Scale length: 24.5"',
      'Frets: Medium jumbo',
      'Pickup: Bridge 16k, Neck 7.8k',
      'Nut: Bone',
      'Potentiometers: 500k',
      'Bridge: Locking roller',
    ],
  },

  arcwind: {
    name: 'ARCWIND',
    slug: 'arcwind',
    heroPreview: '/guitars/arcwind/hero-small.webp',
    heroFull: '/guitars/arcwind/hero-full.webp',
    thumb: '/guitars/arcwind/thumb.webp',
    bg: '/guitars/arcwind/bg.webp',
    galleryManifest: '/guitars/arcwind/gallery/manifest.json',
    images: ['/guitars/arcwind/gallery/1_w800.jpg'],
    specs: [
      'Body: Basswood',
      'Neck: Maple',
      'Fretboard: Rosewood',
      'Construction: Set-in',
      'Fretboard radius: 10"',
      'Scale length: 24.5"',
      'Frets: 22 jumbo',
      'Pickup: Bridge 16.5k, Neck 7.5k',
      'Bridge: Floyd Rose',
      'Tremolo: Double-locking',
      'Potentiometers: 500k',
    ],
  },

  clawtooth: {
    name: 'CLAWTOOTH',
    slug: 'clawtooth',
    heroPreview: '/guitars/clawtooth/hero-small.webp',
    heroFull: '/guitars/clawtooth/hero-full.webp',
    thumb: '/guitars/clawtooth/thumb.webp',
    bg: '/guitars/clawtooth/bg.webp',
    galleryManifest: '/guitars/clawtooth/gallery/manifest.json',
    images: ['/guitars/clawtooth/gallery/1_w800.jpg'],
    specs: [
      'Body: Mahogany',
      'Neck: Mahogany',
      'Carve top',
      'Scale length: Short',
      'Frets: 22 jumbo',
      'Pickup: Bridge 16k, Neck 7.5k',
      'Construction: String-through body',
      'Custom headstock: Custom headstock',
      'Fretboard radius: 12"',
      'Potentiometers: 500k',
    ],
  },

  thunderpig: {
    name: 'THUNDERPIG',
    slug: 'thunderpig',
    heroPreview: '/guitars/thunderpig/hero-small.webp',
    heroFull: '/guitars/thunderpig/hero-full.webp',
    bg: '/guitars/thunderpig/bg.webp',
    thumb: '/guitars/thunderpig/thumb.webp',
    galleryManifest: '/guitars/thunderpig/gallery/manifest.json',
    images: [
      '/guitars/thunderpig/gallery/1_w800.jpg',
      '/guitars/thunderpig/gallery/2_w800.jpg',
      '/guitars/thunderpig/gallery/3_w800.jpg',
    ],
    specs: [],
    testimonial:
      "“I've never owned a bass I loved this much. I've played more bass in the last 48 hours than I have in the last 5 years.” — Nate",
  },
};

export const ALL = Object.values(GUITARS).map((g) => g.slug);
