export const GUITARS = {
  warpig: {
    name: 'WARPIG',
    slug: 'warpig',
    heroPreview: '/guitars/warpig/hero-small.webp',
    heroFull: '/guitars/warpig/hero-full.webp',
    thumb: '/guitars/warpig/thumb.webp',
    bg: '/guitars/warpig/bg.webp',
    bgFallback: '/guitars/warpig/bg.jpg',
    galleryManifest: '/guitars/warpig/gallery/manifest.json',
    images: [
      '/guitars/warpig/gallery/1_w800.jpg',
      '/guitars/warpig/gallery/2_w800.jpg',
      '/guitars/warpig/gallery/3_w800.jpg',
      '/guitars/warpig/gallery/4_w800.jpg',
      '/guitars/warpig/gallery/5_w800.jpg',
      '/guitars/warpig/gallery/6_w800.jpg',
    ],
    specs: [
      'Mahogany body',
      'Maple neck',
      'Rosewood fretboard',
      'Set-in construction',
      '10" fretboard radius',
      '24.5" scale length',
      '22 jumbo frets',
      'Bridge pickup 16.5k',
      'Neck pickup 7.5k',
      'Bone nut',
      '500k pots',
      'Locking roller bridge',
    ],
  },

  specter: {
    name: 'SPECTER',
    slug: 'specter',
    heroPreview: '/guitars/specter/hero-small.webp',
    heroFull: '/guitars/specter/hero-full.webp',
    thumb: '/guitars/specter/thumb.webp',
    bg: '/guitars/specter/bg.webp',
    bgFallback: '/guitars/specter/bg.jpg',
    galleryManifest: '/guitars/specter/gallery/manifest.json',
    images: [
      '/guitars/specter/gallery/1_w800.jpg',
      '/guitars/specter/gallery/2_w800.jpg',
      '/guitars/specter/gallery/3_w800.jpg',
    ],
    specs: [
      'Double cutaway mahogany body',
      'Maple neck',
      'Rosewood fretboard',
      'Pearl trapezoid inlays',
      'Set-in construction',
      '12" fretboard radius',
      '24.5" scale length',
      'Medium jumbo frets',
      'Bridge pickup 16k',
      'Neck pickup 7.8k',
      'Bone nut',
      '500k pots',
      'Locking roller bridge',
    ],
  },

  arcwind: {
    name: 'ARCWIND',
    slug: 'arcwind',
    heroPreview: '/guitars/arcwind/hero-small.webp',
    heroFull: '/guitars/arcwind/hero-full.webp',
    thumb: '/guitars/arcwind/thumb.webp',
    bg: '/guitars/arcwind/bg.webp',
    bgFallback: '/guitars/arcwind/bg.jpg',
    galleryManifest: '/guitars/arcwind/gallery/manifest.json',
    images: ['/guitars/arcwind/gallery/1_w800.jpg'],
    specs: [
      'Basswood body',
      'Maple neck',
      'Rosewood fretboard',
      'Set-in construction',
      '10" fretboard radius',
      '24.5" scale length',
      '22 jumbo frets',
      'Bridge pickup 16.5k',
      'Neck pickup 7.5k',
      'Floyd Rose',
      'Double-locking tremolo',
      '500k pots',
    ],
  },

  clawtooth: {
    name: 'CLAWTOOTH',
    slug: 'clawtooth',
    heroPreview: '/guitars/clawtooth/hero-small.webp',
    heroFull: '/guitars/clawtooth/hero-full.webp',
    thumb: '/guitars/clawtooth/thumb.webp',
    bg: '/guitars/clawtooth/bg.webp',
    bgFallback: '/guitars/clawtooth/bg.jpg',
    galleryManifest: '/guitars/clawtooth/gallery/manifest.json',
    images: ['/guitars/clawtooth/gallery/1_w800.jpg'],
    specs: [
      'Mahogany body',
      'Mahogany neck',
      'Carve top',
      'Short scale length',
      '22 jumbo frets',
      'Bridge pickup 16k',
      'Neck pickup 7.5k',
      'String-through body',
      'Custom headstock',
      '12" fretboard radius',
      '500k pots',
    ],
  },
};

export const ALL = Object.values(GUITARS).map((g) => g.slug);
