export const GUITARS = {
  warpig: {
    name: 'WARPIG',
    slug: 'warpig',
    hero: '/guitars/warpig/hero.png',
    thumb: '/guitars/warpig/thumb.png',
    images: ['/guitars/warpig/1.jpg', '/guitars/warpig/2.jpg'],
    specs: [
      'Mahogany body',
      'Maple neck',
      'Rosewood fretboard',
      'Set-in construction',
      '10" fretboard radius',
      '24.5" scale length',
      '22 jumbo frets',
      'Bridge pickup 16.5k',
      'Neck pickup 7.5k',
      'Bone nut',
      '500k pots',
      'Locking roller bridge',
    ],
  },

  thunderpig: {
    name: 'THUNDERPIG',
    slug: 'thunderpig',
    hero: '/guitars/thunderpig/hero.jpg',
    thumb: '/guitars/thunderpig/thumb.jpg',
    images: ['/guitars/thunderpig/1.jpg', '/guitars/thunderpig/2.jpg'],
    specs: [],
    testimonial:
      "“I've never owned a bass I loved this much. I've played more bass in the last 48 hours than I have in the last 5 years.” — Nate",
  },

  specter: {
    name: 'SPECTER',
    slug: 'specter',
    hero: '/guitars/specter/hero.png',
    thumb: '/guitars/specter/thumb.png',
    images: ['/guitars/specter/1.jpg', '/guitars/specter/2.jpg', '/guitars/specter/3.jpg'],
    specs: [
      'Double cutaway mahogany body',
      'Maple neck',
      'Rosewood fretboard',
      'Pearl trapezoid inlays',
      'Set-in construction',
      '12" fretboard radius',
      '24.5" scale length',
      'Medium jumbo frets',
      'Bridge pickup 16k',
      'Neck pickup 7.8k',
      'Bone nut',
      '500k pots',
      'Locking roller bridge',
    ],
  },

  clawtooth: {
    name: 'CLAWTOOTH',
    slug: 'clawtooth',
    hero: '/guitars/clawtooth/hero.png',
    thumb: '/guitars/clawtooth/thumb.png',
    images: ['/guitars/clawtooth/1.jpg'],
    specs: [
      'Mahogany body',
      'Mahogany neck',
      'Carve top',
      'Short scale length',
      '22 jumbo frets',
      'Bridge pickup 16k',
      'Neck pickup 7.5k',
      'String-through body',
      'Custom headstock',
      '12" fretboard radius',
      '500k pots',
    ],
  },

  arcwind: {
    name: 'ARCWIND',
    slug: 'arcwind',
    hero: '/guitars/arcwind/hero.png',
    thumb: '/guitars/arcwind/thumb.png',
    images: ['/guitars/arcwind/1.jpg'],
    specs: [
      'Basswood body',
      'Maple neck',
      'Rosewood fretboard',
      'Set-in construction',
      '10" fretboard radius',
      '24.5" scale length',
      '22 jumbo frets',
      'Bridge pickup 16.5k',
      'Neck pickup 7.5k',
      'Floyd Rose',
      'Double-locking tremolo',
      '500k pots',
    ],
  },
};

export const ALL = Object.values(GUITARS).map((g) => g.slug);
